defaults:
  - attacks: attacks
  - datasets: datasets
  - models: models
  - defenses: defenses
  - runtime_defenses: runtime_defenses
  - paths
  - override hydra/launcher: a100h100.yaml
  - _self_

hydra:
  run:
    dir: ${root_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  job:
    chdir: true
  sweep:
    dir: ${root_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/

name: testing
save_dir: ${root_dir}/outputs/  # place to store results
inference_save_dir: ${root_dir}/inference_results/  # place to store inference results
jailbreak_save_dir: ${root_dir}/jailbreaks/  # place to store jailbreak results
embed_dir: ${root_dir}/embeddings/  # place to store embeddings for emebdding attacks
overwrite: false

classifiers: ["strong_reject"]  # anything from judgezoo

# Top-level generation config for easier overriding
generation_config:
  temperature: 0.0
  top_p: 1.0
  top_k: 0
  max_new_tokens: 256
  num_return_sequences: 1

# overrides for parallelism
attack: gcg
dataset: adv_behaviors
model: meta-llama/Meta-Llama-3.1-8B-Instruct 
defense: none
runtime_defense: none
